---

- name: Install Docker and enable Docker socker
  hosts: servers
  become: true
  tasks:

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user qjltbarquilla to the docker group
      user:
        name: qjltbarquilla
        groups: docker
        append: yes

    - name: Ensure Docker socket is present and accessible
      command: stat /var/run/docker.sock
      register: docker_socket_stat
      ignore_errors: yes

    - name: Set permissions on Docker socket
      file:
        path: /var/run/docker.sock
        mode: '777'
        owner: root
        group: docker
      when: docker_socket_stat.rc == 0
