---

- name: Build Docker image for web (Apache) and DB (MariaDB) server
  hosts: server1
  become: true
  tasks:

    - name: Ensure Docker SDK for Python is installed
      pip:
        name: docker
        state: present

    - name: Copy Docker file to server1
      copy:
        src: /home/qjltbarquilla/Activity-11-Containerization/Docker_File/
        dest: /home/qjltbarquilla/Activity-11-Containerization/Docker_File/
        owner: qjltbarquilla
        mode: '0755'

    - name: Build Docker image
      docker_image:
        source: build
        build:
          path: /home/qjltbarquilla/Activity-11-Containerization/Docker_File
          dockerfile: Dockerfile
          pull: yes
        name: my_web_db_server
        tag: latest
        state: present
